server:
  port: 8888
  servlet:
    context-path: /family-care
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:13306/family_care?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: 127.0.0.1
    #password:
    port: 16379
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-wait: -1
        max-active: 8
  security:
    user:
      password: family_care_admin
      name: admin
logging:
  config: file:${API_CONFIG}/api_logback.xml